### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sqrt'

### ISSUE THREAD

**Issue by zuinelena3** [theislab/scgen#101]
Hi,
Thanks for your nice work!
I'm running the batch removal tutorial provided in:
https://scgen.readthedocs.io/en/stable/tutorials/scgen_batch_removal.html

But some errors appear: 

vae.batch_removal()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elena/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scgen/_scgen.py", line 220, in batch_removal
  File "/home/elena/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/elena/.local/lib/python3.10/site-packages/scvi/model/base/_vaemixin.py", line 304, in get_latent_representation
    qz: Distribution = Normal(qzm, qzv.sqrt())
AttributeError: 'NoneType' object has no attribute 'sqrt'

vae.get_latent_representation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elena/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/elena/.local/lib/python3.10/site-packages/scvi/model/base/_vaemixin.py", line 304, in get_latent_representation
    qz: Distribution = Normal(qzm, qzv.sqrt())
AttributeError: 'NoneType' object has no attribute 'sqrt'

Here are my packages version:
anndata             0.10.9
scanpy              1.10.3
scgen                2.1.1
h5py                  3.12.1
numpy              1.26.4
pandas             2.2.3
scvi                  1.2.0
torch                 2.4.1+cu121

Python 3.10.12 

Best wishes,
Elena

**Comment by Dexterssssss** [comment]
I'm having the same problem as you with get_latent_representation() 'AttributeError: 'NoneType' object has no attribute 'sqrt'''

**Comment by PrachTecha** [comment]
Hi, I found a work around this by changing line 302 and 303 from [path to your site-packages]/scvi/model/base/_vaemixin.py file ("/home/elena/.local/lib/python3.10/site-packages/scvi/model/base/_vaemixin.py" in your case) to:
                qzm: Tensor = outputs.get(MODULE_KEYS.QZM_KEY if MODULE_KEYS.QZM_KEY in outputs else 'qz_m')
                qzv: Tensor = outputs.get(MODULE_KEYS.QZV_KEY if MODULE_KEYS.QZV_KEY in outputs else 'qz_v')

I think this is because the keys in 'outputs' generated from scGEN are different from MODULE_KEYS for 'qzm' and 'qzv'.

**Comment by zuinelena3** [comment]
@PrachTecha It works now. Thank you a lot!
