### ISSUE TITLE
dependencies update required

### ISSUE THREAD

**Issue by janursa** [theislab/scgen#97]
`updated`: if installed using git, it imports successfully. seems like the new updates are not published to pip

On `python=3.10`, installed `pip install scgen`, when i `import scgen`, i get
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/beegfs/desy/user/nourisaj/miniforge3/lib/python3.10/site-packages/scgen/__init__.py", line 3, in <module>
    from ._scgenvae import SCGENVAE
  File "/beegfs/desy/user/nourisaj/miniforge3/lib/python3.10/site-packages/scgen/_scgenvae.py", line 4, in <module>
    from scvi._compat import Literal
ModuleNotFoundError: No module named 'scvi._compat'
```

**Comment by alinaselega** [comment]
Same error on `python=3.11` with `pip install scgen` installation

**Comment by lxzcpro** [comment]
I use python=3.9 and torch=2.1 with
`pip install git+https://github.com/theislab/scgen.git`
and the tutorial works on my local server

**Comment by steamed-stuffed-bun** [comment]
@lxzcpro  I can't find your tutorial work in your GitHub repository. Can you tell me the full path to the tutorial work?

**Comment by lxzcpro** [comment]
> [@lxzcpro](https://github.com/lxzcpro) I can't find your tutorial work in your GitHub repository. Can you tell me the full path to the tutorial work?

It has been a long time since I used this repo. But I think just the environmental problem that prevents the scgen work.  You may try creating a new conda environment with python=3.9 and then install torch 2.1 and `pip install git+https://github.com/theislab/scgen.git` to run the tutorial in Jupyter notebook? And then it works for me.
